export const SET_TOKEN = 'SET_TOKEN';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_POSITION = 'SET_POSITION';
export const SET_CART_SHOPS = 'SET_CART_SHOPS';
export const SET_ADDRESSES = 'SET_ADDRESSES';
export const SET_RECEIVE_ADDRESS = 'SET_RECEIVE_ADDRESS';
