export const SET_TOKEN = 'SET_TOKEN';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_POSITION = 'SET_POSITION'; // 当前定位
export const SET_CART_SHOPS = 'SET_CART_SHOPS';
export const SET_ADDRESSES = 'SET_ADDRESSES';
export const SET_RECEIVE_ADDRESS = 'SET_RECEIVE_ADDRESS';
export const SET_FIRST_OPEN = 'SET_FIRST_OPEN';
export const SET_RECEIVED_POSITION = 'SET_RECEIVED_POSITION'; // 收货定位
